name: Switch Xcode

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - run: sudo xcode-select -s /Applications/Xcode_14.1.app
      
      - run: xcodebuild -version
